### ISSUE TITLE
Add Content-Type header to documentation

### ISSUE THREAD

**Issue by sbalje** [MicrosoftDocs/partner-center-sdk#10]
Using the REST API with the headers described in
https://docs.microsoft.com/en-us/partner-center/develop/headers
is not sufficient when sending a POST request as described in
https://docs.microsoft.com/en-us/partner-center/develop/confirm-customer-consent

An additional header is required:
Content-Type: application/json

Failing to include the header results in a response with status code 500, providing an error code 600003 and a message "Unexpected service error". This may apply to resources other than "Agreement".

If it applies to POST requests in general, I suggest adding it to the 'Partner Center REST headers' page.  If only for certain scenarios, then mention the header those places.

I spent a fair amount of time trying to figure out the not-so-helpful error message, building a custom PHP integration. The Java SDK does send the Content-Type header, which is how I was able to see that the REST request example in the documentation, is missing a header.

**Comment by isaiahwilliams** [comment]
Hi @sbalje, 

Thank you bring this issue to our attention. You are correct the accept and content type headers should be set for each request made to the Partner Center API. I will review the documentation and make the appropriate updates.

**Comment by isaiahwilliams** [comment]
Hi @sbalje, 

We just merged an update that included the changes to correct this documentation. I wanted to thank you for bring it to our attention. 

@Xansky we can close this issues.

**Comment by Xansky** [comment]
Thanks!
