### ISSUE TITLE
Incorrect Title 

### ISSUE THREAD

**Issue by anjali2817** [MicrosoftDocs/partner-center-sdk#100]
Hello team ,
Upon clicking the 'Update a self serve policy' page re-directs to incorrect title : ''Create a SelfServePolicy''

https://docs.microsoft.com/en-us/partner-center/develop/update-a-self-serve-policy

The contents of the page are correct ,  the  title needs to change from Create a SelfServePolicy to Update a SelfServePolicy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62228803-d18a-967b-195d-5c82013a1ddf
* Version Independent ID: 2ffad56c-6724-26cd-a8bf-26bc2234123c
* Content: [Update a self serve policy - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/update-a-self-serve-policy#feedback)
* Content Source: [develop/update-a-self-serve-policy.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/update-a-self-serve-policy.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-sdk**
* GitHub Login: @JasonWHowell
* Microsoft Alias: **jasonh**

**Comment by JasonWHowell** [comment]
Thanks! I'll fix the doc.

**Comment by anjali2817** [comment]
Thankyou so much for taking time off to fix it .

I see the change now .

[cid:image003.jpg@01D62AE3.5B234830]

Regards,
Anjali

Thanks and Regards,

[MSFT_logo_Gray DE sized SIG1.png]

Anjali Susai


Support Engineer
Partner Center/API
Customer Service & Support (CSS)
Office: US: +1(855)425-1603  - Extn:- 80134
Days: Tue-Sat Work Hours: 1:00 PM to 10:30 AM GMT
Email: ansusai@microsoft.com<mailto:ansusai@microsoft.com>
Backupemail:Thiagarajan.Sundarapandian@microsoft.com<mailto:Thiagarajan.Sundarapandian@microsoft.com>
Leads: PC_API@microsoft.com<mailto:PC_API@microsoft.com>
Manager: Ankur : anmanori@microsoft.com<mailto:anmanori@microsoft.com>
