### ISSUE TITLE
Retrieve Sandbox username

### ISSUE THREAD

**Issue by taguada** [MicrosoftDocs/partner-center-sdk#101]
There is no option to retrieve what was Sandbox username used when creating it. After creating, the only information showed on portal are Account ID and Sandbox domain. How can we reset it or crete a new one?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2204551-94a8-6690-4cc6-635e3ca74979
* Version Independent ID: 0e67a756-790d-c97f-5ca4-a62f84d26b41
* Content: [Set up API access in Partner Center - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/set-up-api-access-in-partner-center?redirectedfrom=MSDN)
* Content Source: [develop/set-up-api-access-in-partner-center.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/set-up-api-access-in-partner-center.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-sdk**
* GitHub Login: @JasonWHowell
* Microsoft Alias: **jasonh**

**Comment by JasonWHowell** [comment]
Sorry, we are slow to monitor and reply here. Consider asking the question in the Q&A forum. https://docs.microsoft.com/en-us/answers/topics/partner-center-api.html

**Comment by vijvala** [comment]
@taguada  There is no option for Sandbox partners to reset or create a new one. If you need assistance, please open a support ticket and we will help you. 

This is a known issue for not retrieving a Sandbox User name once created. We are internally tracking this issue.
