### ISSUE TITLE
REST /customers/{customer_id}/subscriptions endpoint does not return all subscriptions

### ISSUE THREAD

**Issue by Woody1193** [MicrosoftDocs/partner-center-sdk#102]
When requesting unbilled usage from the `https://api.partnercenter.microsoft.com/v1/invoices/unbilled/lineitems?provider=onetime&invoicelineitemtype=usagelineitems&currencycode=jpy&period=previous` endpoint. I attempted to retrieve the subscription by calling the `https://api.partnercenter.microsoft.com/v1/customers/{customer_id}/subscriptions/{subscription_id}` with the customer ID and subscription ID that were contained on the usage item and was able to retrieve that subscription. However, calling the `https://api.partnercenter.microsoft.com/v1/customers/{customer_id}/subscriptions` endpoint does not show the subscription. Is this expected behavior and, if so, why? The documentation does not provide any information on this.

**Comment by JasonWHowell** [comment]
Sorry, we are slow to monitor and reply here. Consider asking the question in the Q&A forum. https://docs.microsoft.com/en-us/answers/topics/partner-center-api.html

**Comment by Woody1193** [comment]
I can't access that forum for some reason.

**Comment by vijvala** [comment]
@Woody1193 The best way to get a response to partner questions is open a customer support ticket. I am closing this ticket, appreciate if you can follow up with CS by following the directions on CS support. https://docs.microsoft.com/en-us/partner-center/report-problems-with-partner-center
