### ISSUE TITLE
URI parameter subscription-id description

### ISSUE THREAD

**Issue by andrepiresrep** [MicrosoftDocs/partner-center-sdk#103]
[Enter feedback here]
Hello, in the description of the URI parameter subscription-id it is stated "A GUID formatted string that identifies the trial subscription."  However, the update subscription support contact procedure  is valid not only for trial subscriptions correct? Does this also include an azure plan subscription? And if it is possible to update the azure plan subscription should I pass the subscription id of the azure plan itself or the subscription that appears under it?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9459732e-a429-072a-f72f-2c06b0ae7b7c
* Version Independent ID: bb29d968-419c-1bd6-ebc2-a76d98c560f7
* Content: [Update a subscription's support contact - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/update-a-subscription-s-support-contact)
* Content Source: [develop/update-a-subscription-s-support-contact.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/update-a-subscription-s-support-contact.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-sdk**
* GitHub Login: @JasonWHowell
* Microsoft Alias: **jasonh**

**Comment by JasonWHowell** [comment]
Sorry, we are slow to monitor and reply here. Consider asking the question in the Q&A forum. https://docs.microsoft.com/en-us/answers/topics/partner-center-api.html

**Comment by andrepiresrep** [comment]
Hello Jason,
After reaching out to partner center, I was indicated that it is not possible to update the subscription support contact of an azure plan subscription, so that is why I was getting this error.

**Comment by JasonWHowell** [comment]
Thanks for the followup. Sharing that may help others who run across the same thing in the future. 

I'll close this issue, assuming the answer you found was what was needed. Thanks! Jason
#please-close
