### ISSUE TITLE
Get customer subscription ConvertFrom-Json : Invalid JSON primitive: .

### ISSUE THREAD

**Issue by motim6026** [MicrosoftDocs/partner-center-sdk#104]
Hi

im try to get customer subscriptions using call to API 

`$SubscribedSKU = Invoke-WebRequest -Uri https://api.partnercenter.microsoft.com/v1/customers/{customerid}/subscriptions -Method Get -Headers $headers;`
and when try to pars response Content from json (ConvertFrom-Json) i get this error:
`ConvertFrom-Json : Invalid JSON primitive: .`

i copy the response to notepad and i see tha first char in the json is "?"
attach screenshot from notepad
![image](https://user-images.githubusercontent.com/27952544/84999022-41101480-b159-11ea-8d19-69c64024d62b.png)

any idea why it's happening? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16a4c102-0a9f-5c3d-8e45-4d3db464a739
* Version Independent ID: 9955ec7f-e7c3-0895-2ec7-3f0e5b9c9f1b
* Content: [Get a customer's subscriptions - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/get-all-of-a-customer-s-subscriptions)
* Content Source: [develop/get-all-of-a-customer-s-subscriptions.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/get-all-of-a-customer-s-subscriptions.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-sdk**
* GitHub Login: @JasonWHowell
* Microsoft Alias: **jasonh**

**Comment by motim6026** [comment]
Partner center api get customer subscription parsing error

**Comment by JasonWHowell** [comment]
Sorry, we are slow to monitor and reply here. Consider asking the question in the Q&A forum. https://docs.microsoft.com/en-us/answers/topics/partner-center-api.html

**Comment by isaiahwilliams** [comment]
@motim6026 that is the [byte order mark](https://en.wikipedia.org/wiki/Byte_order_mark). This value is used to identify the encoding. If you are interested you can leverage the Partner Center PowerShell module instead of making the raw requests as one way to avoid having to contend with this.

**Comment by JasonWHowell** [comment]
#please-close
