### ISSUE TITLE
Item not in Azure Rate Card

### ISSUE THREAD

**Issue by Woody1193** [MicrosoftDocs/partner-center-sdk#107]
Recently, I was attempting to process an invoice but was unable to because one of the line items did not appear in the Azure Rate Card. The item in question had a resource ID of 1E5F436B-6034-460F-B33D-0ADA08C4349B, a service name of Azure Cognitive Search and a resource name of Standard S2 Units and a region of JA West. Looking at the Microsoft Azure product information, [here](https://azure.microsoft.com/en-us/pricing/details/search/), I see that this item is available. So, why is it not in the rate card?

**Comment by vijvala** [comment]
@brentserbus Can you please look into this?

**Comment by vijvala** [comment]
@Woody1193  please open a support ticket to get your questions answered immediately. this is not something we use for tracking partner queries.

**Comment by brentserbus** [comment]
Bug logged 28576544 to track this to the ratecard team.  btw, in the mean time you can see this in the modern consumption azure plan price list.
