### ISSUE TITLE
Code Examples for App + User REST API Outdated due to new MFA Req for Partner Center

### ISSUE THREAD

**Issue by jhughes17** [MicrosoftDocs/partner-center-sdk#11]
Testing the changes to come for the new MFA requirements, i enabled multi factor on my user account. Now greeted with this error from our winService which process all of our CSP Requests 

"{\"error\":\"interaction_required\",\"error_description\":\"AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access 'fa3d9a0c-3fb0-42cc-9193-47c7ecd2edbd'......

The examples in partner-center-authentication.md to access the REST API with app+user are no longer relevant. Will any examples of how to preserve apps already running this way be made? aka services interacting with REST API with App+User.

**Comment by isaiahwilliams** [comment]
Hi @jhughes17, 

Thank you for opening this request. Unfortunately that article has not been updated to reflect the new recommendation for authenticating using the new secure app model. We are actively working to update that document. Once you have enabled multifactor authentication for your account you need to modify the method you are using to obtain the access token. Considering that multifactor authentication is interactive you will need to have a process to register the credentials and store the resulting refresh token. Our recommendation is to leverage the [authorization code flow](https://docs.microsoft.com/azure/active-directory/develop/v1-protocols-oauth-code). 

There is additional guidance available through Yammer. I would recommend you review the information that has been shared there while we work to get this page updated.

**Comment by MattMcd-NeoCloud** [comment]
Are there any REST examples or resources out there? The App + User Authentication had REST examples and I used these to originally set up Authentication. Now I have to switch to accept MFA, but there are only Java and .NET examples.
