### ISSUE TITLE
Does not allow update

### ISSUE THREAD

**Issue by xxankitxx** [MicrosoftDocs/partner-center-sdk#121]
I have tried updating a customer using all the codes provided. It doesn't allow me to update it at all. When I fetch the current qualifications, I get this :-
{"qualifications":[]}
When I try updating, I get this :-
1) For code 1

{
    "code": 400,
    "message": "Access denied.",
    "description": "Access denied.",
    "errorName": "AccessDeniedCode400BadRequestFromPartnerApi",
    "isRetryable": false,
    "parameters": {},
    "errorMessageExtended": "InternalErrorCode=400"
}

2) For Code 2

{
    "code": 600002,
    "message": "Partner not allowed to set qualification Nonprofit",
    "description": "Partner not allowed to set qualification Nonprofit",
    "errorName": "InvalidInput",
    "isRetryable": false,
    "parameters": {},
    "errorMessageExtended": "InternalErrorCode=600002"
}

3) For code 3

{
    "qualification": "GovernmentCommunityCloud",
    "vettingStatus": "Denied",
    "vettingCreateDate": "2021-02-05T12:22:39.4257014+00:00"
}

4) For code 0

{
    "code": 600002,
    "message": "Partner not allowed to set qualification None",
    "description": "Partner not allowed to set qualification None",
    "errorName": "InvalidInput",
    "isRetryable": false,
    "parameters": {},
    "errorMessageExtended": "InternalErrorCode=600002"
}

Please explain as to what has to be done. I am at my wit's end. Everytime I fetch qualifications, I get a blank object. When I try updating, I get the above responses.

**Comment by jasongroce** [comment]
Thanks @xxankitxx for reaching out. Unfortunately, GitHub is not a good forum for getting help with technical issues like this. Yammer is a good place to post your issue. If you prefer not to do so, you could reach out to our support team who can take a look at this.
