### ISSUE TITLE
Is App-Only Auth Not Actually Supported Anymore?

### ISSUE THREAD

**Issue by MatthewPinheiro** [MicrosoftDocs/partner-center-sdk#130]
Hello,

For the past few days I've been attempting to get my daemon running using app-only authentication. This daemon is meant to do only one thing through the Partner Center API, and that's pull a list of our customers. 

At least according to the prerequisites of [this documentation on pulling a list of customers](https://docs.microsoft.com/en-us/partner-center/develop/get-a-list-of-customers#prerequisites), doing so via app-only auth should be possible (note my emphasis in the following quote):

> - Credentials as described in Partner Center authentication. This scenario supports authentication **_with both standalone App_** and App+User credentials.

Though I have gotten this to work with app+user authentication, I've been unable to do so with app-only auth. For the latter, I mostly followed [this doc on setting up API Access](https://docs.microsoft.com/en-us/partner-center/develop/set-up-api-access-in-partner-enter) and [this doc on app-only auth via REST](https://docs.microsoft.com/en-us/partner-center/develop/partner-center-authentication#rest-app-only-authentication), but despite being able to retrieve an access token on both integration and primary accounts, both tokens produce a `401 (invalid grant)` when trying to use them against the `/v1/customers` API path. 

I'm starting to think app-only auth may actually be impossible in the first place, as when I head to the AAD Portal and check the API Permissions available for the "Partner Center Web App" (as well as the other two similarly-named "Microsoft Partner Center" and "Microsoft Partner" APIs) only a single permission is available to select--_delegated_ "user_impersonation". 

So if delegated permissions are the only type available in the AADP at all, is app-only auth no longer supported? Or am I totally missing something?

**Comment by JasonWHowell** [comment]
Hi @MatthewPinheiro this isn't a great place to post issues, since I don't have the technical expertise to help you. 

@dineshvu may know more, or you can work with support to confirm the scenario. If the doc is wrong in some way and the research is done, I'm glad to discuss at that point what we can change.

**Comment by MatthewPinheiro** [comment]
Hi @JasonWHowell 

Thanks for the response. I'm fairly certain that the docs are wrong, but I haven't spoken to support about this. Would be interested in hearing more from @dineshvu if he knows more, but in the meantime here's a somewhat concise explanation of why I think the docs are wrong:

Certain docs state that app-only authentication is possible for certain scenarios/endpoints of the Partner Center API. However, perhaps since the introduction of the secure application model, I think this might no longer be the case. I base this on my own testing and the fact that application permissions (as opposed to delegated permissions) are *not* available for the Partner Center API within the Active Directory Portal (ADP). This holds true even on a brand new sandbox integration account with its default settings, which leads me to believe that the lack of application permissions in the ADP is *not* related to my environment, but is just not possible. 

Of course though, there's always the possibility that my reading comprehension has sunk to new lows and the answer has been in front of me this whole time. A personal favorite possibility tbh.

**Comment by dineshvu** [comment]
@MatthewPinheiro - We tested this using our own accounts and our documentation seems accurate. We do support App only and App + User authentication. I strongly recommend reaching out via support route or if you want to debug live please work with @vijvala to co-ordinate a debugging session. 

I would like to re-iterate what Jason stated, github is NOT a good forum for discussing such issues. Yammer is probably better if you dont like Yammer reaching out to our support team will also be better forum.

**Comment by jasongroce** [comment]
Closing based on the above conversation.
