### ISSUE TITLE
Response does not match documentation

### ISSUE THREAD

**Issue by anarghya-das** [MicrosoftDocs/partner-center-sdk#16]
The response body mentioned in the documentation states that the response will be in the JSON format: 

{
    "education"
}

1) This is an invalid JSON format.
2) The actual response received was in the following format (as represented by VSCode): "education"

The response fails to parse as it is not a valid json string. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6cdb140-e97c-14ab-56d2-8ff737e886c4
* Version Independent ID: 0d875870-3887-699c-1f86-d8e37cc67af6
* Content: [Get a customer's qualification - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/get-a-customer-s-qualification#feedback)
* Content Source: [develop/get-a-customer-s-qualification.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/get-a-customer-s-qualification.md)
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by lauradolan** [comment]
Thanks for your feedback. We've updated the documentation: https://docs.microsoft.com/en-us/partner-center/develop/get-a-customer-s-qualification. The correct response is `"education"`.
