### ISSUE TITLE
authnmethodsreferences claim (enforcement)

### ISSUE THREAD

**Issue by lochiiconnectivity** [MicrosoftDocs/partner-center-sdk#18]
"How will the requirement for multi-factor authentication be enforced? This requirement will be enforced by ensuring that a claim of type http://schemas.microsoft.com/claims/authnmethodsreferences with a value of mfa is present. If it is not then authentication will be denied" - should the value not be "http://schemas.microsoft.com/claims/multipleauthn" as opposed to simply "mfa" ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83b890e5-4406-2862-bcf3-cabd6e90d9cb
* Version Independent ID: 8383e9ca-8319-70a8-a32c-d03e63d5a1f9
* Content: [Partner Center authentication - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/partner-center-authentication?tabs=dotnet-app-only%2Cdotnet-app-user%2Cdotnet-csp%2Cdotnet-cpp#feedback)
* Content Source: [develop/partner-center-authentication.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/partner-center-authentication.md)
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by isaiahwilliams** [comment]
@lochiiconnectivity it will be a check for the MFA claim. So, you are correct it will be looking for the value MFA in the amr. The value you referenced is how .NET translates the claim values.
