### ISSUE TITLE
REST Example

### ISSUE THREAD

**Issue by MattMcd-NeoCloud** [MicrosoftDocs/partner-center-sdk#19]
Can a REST sample be posted for this? I originally followed the App + User REST examples, but now that MFA is required, I have to switch to using the Secure Application Model. However there are only .NET and Java examples and I am struggling to convert what I need to do into REST requests. Seems like an oversight for this page since we are now forced to change how our Apps authenticate and there isn't an example along the lines of the original REST examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad81757a-da98-492e-aa46-cd920709432e
* Version Independent ID: fbf50fa1-8698-5e30-483b-2408426d349d
* Content: [Enable secure application model - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/enable-secure-app-model#feedback)
* Content Source: [develop/enable-secure-app-model.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/enable-secure-app-model.md)
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by lauradolan** [comment]
REST examples and instructions have been added to this topic https://docs.microsoft.com/en-us/partner-center/develop/enable-secure-app-model#rest
