### ISSUE TITLE
Linked page doesn't contain information this page state it does

### ISSUE THREAD

**Issue by dusan-rd** [MicrosoftDocs/partner-center-sdk#20]
Text "See *Authenticate with a certificate* instead of a client secret for more information."
The linked page doesn't have any information about "Authenticate with a certificate".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83b890e5-4406-2862-bcf3-cabd6e90d9cb
* Version Independent ID: 8383e9ca-8319-70a8-a32c-d03e63d5a1f9
* Content: [Partner Center authentication - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/partner-center-authentication?tabs=apponly-dotnet%2Cappuser-dotnet%2Ccsp-dotnet%2Ccpp-dotnet#feedback)
* Content Source: [develop/partner-center-authentication.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/partner-center-authentication.md)
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by lauradolan** [comment]
Thanks for the feedback. We've updated the link on this page.
