### ISSUE TITLE
Powershell, step 2

### ISSUE THREAD

**Issue by maximeplanteemyode** [MicrosoftDocs/partner-center-sdk#22]
$token = New-PartnerAccessToken -Consent -Credential $credential -Resource https://api.partnercenter.microsoft.com -ServicePrincipal

-ServicePrincipal isn't available anymore.

According to https://docs.microsoft.com/en-us/powershell/module/partnercenter/new-partneraccesstoken?view=partnercenterps-1.5
Moreover a TenantId is mandatory if specifying the -Credential flag.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad81757a-da98-492e-aa46-cd920709432e
* Version Independent ID: fbf50fa1-8698-5e30-483b-2408426d349d
* Content: [Enable secure application model - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/enable-secure-app-model#feedback)
* Content Source: [develop/enable-secure-app-model.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/enable-secure-app-model.md)
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by isaiahwilliams** [comment]
@maximeplanteemyode you can find complete documentation on how to implement the Secure Application model using PowerShell [here](https://docs.microsoft.com/partner-center/develop/partner-center-authentication). We will work with the content owners for the documents you referenced to get the PowerShell sections updated.
