### ISSUE TITLE
Custom subscription ID is not being honored

### ISSUE THREAD

**Issue by brooksca** [MicrosoftDocs/partner-center-sdk#24]
Using the following code does not set the subscription ID as expected. 

var subscriptionId = Guid.NewGuid().ToString().ToLower();

            var order = new Order
            {
                ReferenceCustomerId = request.CustomerMicrosoftId,
                LineItems = new List&lt;OrderLineItem&gt;
                {
                    new OrderLineItem
                    {
                        Quantity = request.InitialQuantity,
                        FriendlyName = request.FriendlyName,
                        OfferId =  request.OfferId,
                        ProvisioningContext = new Dictionary&lt;string, string&gt;
                        {
                            ["subscriptionId"] = subscriptionId
                        }
                    }
                }
            };

Once the subscription is created, in the Partner Center dashboard, the subscription ID is completely different.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e699fea-8dd1-5e41-b53d-b14d6db2738b
* Version Independent ID: 325ed4a5-deff-30ab-85bb-711e9789dfc5
* Content: [Create an order - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/create-an-order#feedback)
* Content Source: [develop/create-an-order.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/create-an-order.md)
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by cychua** [comment]
Hi,

When purchasing a new subscription, Partner Center will generate and return the Subscription ID. You can specify it.

The sample you quoted is not to create a subscription. It is to purchase an Azure Reserved Instance. When purchasing an Azure Reserved Instance, you need to specify an existing Azure subscription. This is what the SubscriptionID is for.

Thanks,
Chun Yong
