### ISSUE TITLE
renewsTo	property is not an array

### ISSUE THREAD

**Issue by andrepiresrep** [MicrosoftDocs/partner-center-sdk#26]
Hello, the renewsTo property in the orderLineItem is in fact an object of type RenewsTo instead of an array, however the description of the renewsTo property indicates that it is an array.
https://docs.microsoft.com/en-us/dotnet/api/microsoft.store.partnercenter.models.orders.orderlineitem?view=partnercenter-dotnet-latest
https://docs.microsoft.com/en-us/dotnet/api/microsoft.store.partnercenter.models.orders.renewsto?view=partnercenter-dotnet-latest

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9b9c6f5-6980-b15f-2005-a34dfd6f399a
* Version Independent ID: 408f05f0-49fa-bbba-b856-87ed56e51f19
* Content: [Order resources - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/order-resources)
* Content Source: [develop/order-resources.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/order-resources.md)
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by lauradolan** [comment]
Thanks for your feedback. The renewsTo description has been updated: https://docs.microsoft.com/en-us/partner-center/develop/order-resources#orderlineitem.
