### ISSUE TITLE
Utilization API Dates

### ISSUE THREAD

**Issue by rlisnoff** [MicrosoftDocs/partner-center-sdk#28]
When querying this API, we provide a date range for the results we want to see, but this datetime is when the record was logged to the system which is not reflected at all in the returned results. Is there any way to expose the logged date? That would make understanding the results much easier.

Also, are the dates in the query inclusive, or exclusive?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e9d8c78-41fd-9457-9146-825ecfd807e5
* Version Independent ID: 8d1c6937-2c7b-30bd-883e-296d7c2d8553
* Content: [Get a customer's utilization records for Azure - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/get-a-customer-s-utilization-record-for-azure)
* Content Source: [develop/get-a-customer-s-utilization-record-for-azure.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/get-a-customer-s-utilization-record-for-azure.md)
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by isaiahwilliams** [comment]
The records available through the API will be for when they are emitted into the billing system. To my knowledge there is not an API that will provide the exact time the resource was consumed. The dates used with the query are inclusive
