### ISSUE TITLE
Consent parameter no longer exists

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/partner-center-sdk#29]
Updated to the latest version of the PartnerCenter module and this parameter appears to have moved.

How do we generate access tokens now?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad81757a-da98-492e-aa46-cd920709432e
* Version Independent ID: fbf50fa1-8698-5e30-483b-2408426d349d
* Content: [Enable secure application model - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/enable-secure-app-model)
* Content Source: [develop/enable-secure-app-model.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/enable-secure-app-model.md)
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by jonwbstr** [comment]
Just found another issue with additional information. New module broke the documentation :)

https://github.com/MicrosoftDocs/partner-center-docs-powershell/issues/39

**Comment by o-l-a-v** [comment]
Just cought the same documentation error.
Please start being consistent with documentation vs reality Microsoft!

**Comment by isaiahwilliams** [comment]
@jonwbstr and @o-l-a-v please reference this [article](https://docs.microsoft.com/powershell/partnercenter/multi-factor-auth?view=partnercenterps-2.0) from the Partner Center PowerShell module documentation moving forward. To simplify the documentation the PowerShell steps will be removed from the article in this document set.
