### ISSUE TITLE
Add versionRank field description

### ISSUE THREAD

**Issue by miababii** [MicrosoftDocs/partner-center-sdk#30]
There is a new field into the response body specified on https://docs.microsoft.com/en-us/partner-center/develop/get-customer-agreement-metadata. Please add it's description here, so we can know how and when to use it from code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad740933-6e60-291e-14ba-8a4e81133047
* Version Independent ID: e8a46a09-153a-2eac-1bd0-0aad104a6616
* Content: [Agreement metadata resources - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/agreement-metadata-resources)
* Content Source: [develop/agreement-metadata-resources.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/agreement-metadata-resources.md)
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by cychua** [comment]
The attribute versionRank is for Partner Center Portal use only (Partner Center Portal calls the same API as partner application). We do not expect partners to consume this attribute and hence it is not documented.

Thanks,
Chun Yong
