### ISSUE TITLE
Bug Report: Generated Access Token With Wrong Scopes

### ISSUE THREAD

**Issue by johnz** [MicrosoftDocs/partner-center-sdk#31]
This is not directly related to partner center API, but something to do with using Partner Admin account to access tenant Graph API data (Partner Admin has Delegate Access to the tenant)
----------------------------------------------------------------------
**Actual behavior:**
- Access Token scope is "profile openid email"
----------------------------------------------------------------------
**Expected behavior:** 
- Access Token should have scope "AuditLog.Read.All Directory.Read.All Reports.Read.All SecurityEvents.Read.All User.Read.All profile openid email"
----------------------------------------------------------------------
**Step to reproduce:**
1. Register a new app in Azure portal App registrations
2. Use OAuth 2 v2.0 code grant flow to get access_token and refresh_token
    - login url https://login.microsoftonline.com/{tenantId}/oauth2/v2.0/authorize?client_id={clientId}&response_type=code&redirect_uri=https%3A%2F%2Fabc.ngrok.io%2Fclient-callback&response_mode=query&scope=offline_access+User.Read.All+Reports.Read.All+AuditLog.Read.All+Directory.Read.All+SecurityEvents.Read.All
    - login as Partner Admin and give the app permission to access {tenantId}
    - Partner Admin has Delegate Access to the {tenantId}
3. Got access_token and refresh_token using authorization_code grant_type
    - both {tenantId} and scopes are correct in access_token
4. Use refresh_token to generate new access_token
    - POST https://login.microsoftonline.com/{tenantId}/oauth2/v2.0/token
      Body:  
            client_id={clientId}
            &scope=profile openid email User.Read.All Reports.Read.All AuditLog.Read.All Directory.Read.All SecurityEvents.Read.All
            &refresh_token={refresh_token}
            &grant_type=refresh_token
            &client_secret={clientSecret}  
5. In response the scope is "profile openid email"
    - x-ms-request-id: 953855f8-9d5a-4ad6-aef4-622afb3f6800
    - x-ms-ests-server: 2.1.9587.8 - HKG2 ProdSlices
    - Date: Wed, 30 Oct 2019 07:46:43 GMT

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83b890e5-4406-2862-bcf3-cabd6e90d9cb
* Version Independent ID: 8383e9ca-8319-70a8-a32c-d03e63d5a1f9
* Content: [Partner Center authentication - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/partner-center-authentication)
* Content Source: [develop/partner-center-authentication.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/partner-center-authentication.md)
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by isaiahwilliams** [comment]
Working with the Azure AD on this, would be the best path. The scope in the response is returning what you shared because of what you included in the body. I cannot remember for certain but I do not believe profile and openId should be used as scopes. They are not actual permissions if I remember right.
