### ISSUE TITLE
Quick Q

### ISSUE THREAD

**Issue by Eric-VF** [MicrosoftDocs/partner-center-sdk#32]
Who can we tap if we are having issues deploying this? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83b890e5-4406-2862-bcf3-cabd6e90d9cb
* Version Independent ID: 8383e9ca-8319-70a8-a32c-d03e63d5a1f9
* Content: [Partner Center authentication - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/partner-center-authentication#feedback)
* Content Source: [develop/partner-center-authentication.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/partner-center-authentication.md)
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by cychua** [comment]
For questions around API integration, suggest you start with Microsoft Cloud Partner Community (https://www.yammer.com/cloudpartnercommunity).

Thanks,
Chun Yong
