### ISSUE TITLE
Node Example

### ISSUE THREAD

**Issue by Matt-McDonald-AS** [MicrosoftDocs/partner-center-sdk#34]
Is it possible to get an example of the Secure App Model in Node.js? This would be really helpful!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83b890e5-4406-2862-bcf3-cabd6e90d9cb
* Version Independent ID: 8383e9ca-8319-70a8-a32c-d03e63d5a1f9
* Content: [Partner Center authentication - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/partner-center-authentication#feedback)
* Content Source: [develop/partner-center-authentication.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/partner-center-authentication.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-csp**
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by isaiahwilliams** [comment]
@Matt-McDonald-AS we have shared the details on how to perform the operations using HTTP rest operations. Right now we do not have immediate plans to add samples in different languages. I hope that this helps.

**Comment by JasonWHowell** [comment]
@Matt-McDonald-AS 
Thanks for the question, and sorry for the delay. Isaiah recently provided an answer, and I hope that resolves your question. We'll close the issue for now, but please let us know if you need additional clarification. Thanks! Jason
