### ISSUE TITLE
Upgrade 

### ISSUE THREAD

**Issue by oelabd** [MicrosoftDocs/partner-center-sdk#35]
Can we see a table to of what are the allowed upgrades and what is not allowed ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 967eb19b-7c48-05d7-6769-daed9e5e3592
* Version Independent ID: 4ff2d62b-add7-b6d5-0cdb-6254c9932523
* Content: [Upgrade resources - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/upgrade-resources#feedback)
* Content Source: [develop/upgrade-resources.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/upgrade-resources.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-csp**
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by vijvala** [comment]
@oelabd This has been close to 9 months old, are you still looking for answers? If so you can reach out on Yammer, which you can get better support.
