### ISSUE TITLE
You have a link to an internal document in the "Enable Secure App Model" article

### ISSUE THREAD

**Issue by KirkMunro** [MicrosoftDocs/partner-center-sdk#36]
In https://docs.microsoft.com/en-us/partner-center/develop/enable-secure-app-model#secure-application-model, you have a link to a "Secure Application Model Framework" document that uses an URL that is only available inside of Microsoft. Please provide a URL to a document that external customers can download for review.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad81757a-da98-492e-aa46-cd920709432e
* Version Independent ID: fbf50fa1-8698-5e30-483b-2408426d349d
* Content: [Enable secure application model - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/enable-secure-app-model)
* Content Source: [develop/enable-secure-app-model.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/enable-secure-app-model.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-csp**
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by isaiahwilliams** [comment]
I just confirmed the link in the article tofay is publicly accessible. It will require that you authenticate with your partner credentials. If you are still having issues accessing it, please let us know.
