### ISSUE TITLE
Subscription Updated Event,  what changes trigger this event?

### ISSUE THREAD

**Issue by xdmushui** [MicrosoftDocs/partner-center-sdk#37]
Subscription Updated Event,  what changes trigger this event?
new service, delete service, seat change, scale the virtual machine, license change, cancellation, etc?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9154c92-7c93-a0c8-5e70-24b04b1509ee
* Version Independent ID: 6699ddda-4b29-28aa-cc2b-98c622e7049c
* Content: [Partner Center webhook events - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/partner-center-webhook-events#feedback)
* Content Source: [develop/partner-center-webhook-events.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/partner-center-webhook-events.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-csp**
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by isaiahwilliams** [comment]
The subscription webhook through the Partner Center will be only be triggered when there are commerce level changes. Which means it will not be triggered when resources are created within the subscription, and only when the number of licenses are modified and when the state of the subscription changes.

**Comment by JasonWHowell** [comment]
@xdmushui Thanks for the question, and sorry for the delay. Isaiah recently provided an answer, and I hope that resolves your question. We'll close the issue for now, but please let us know if you need additional clarification. Thanks! Jason
