### ISSUE TITLE
Why not use "native app"? Some clearification would be great

### ISSUE THREAD

**Issue by o-l-a-v** [MicrosoftDocs/partner-center-sdk#38]
This doc does not mention anything about using Partner Center API "native app", which also works perfectly with the Partner Center powershell module. 

* Is native not recommended at all?
* Any scenarios where you would use native app vs web app and vice versa?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2204551-94a8-6690-4cc6-635e3ca74979
* Version Independent ID: 0e67a756-790d-c97f-5ca4-a62f84d26b41
* Content: [Set up API access in Partner Center - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/set-up-api-access-in-partner-center)
* Content Source: [develop/set-up-api-access-in-partner-center.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/set-up-api-access-in-partner-center.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-csp**
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by isaiahwilliams** [comment]
Native applications will work. They were not included in this document for two reasons. The first is that a web application is considered more secure because it requires additional secret value. The second has to deal with simplicity. Our generally recommendation is to use web applications where possible.

**Comment by o-l-a-v** [comment]
A word about in the documentation would be great, I'm sure I'm not the only one wondering about this.

**Comment by JasonWHowell** [comment]
Hi @o-l-a-v  Thanks for the question. Isaiah recently provided an answer, and I hope that resolves your question. We'll close the issue for now, but please let us know if you need additional clarification. Thanks! Jason
