### ISSUE TITLE
Missing information on Azure Plan lifecycle

### ISSUE THREAD

**Issue by eric-jenouvrier** [MicrosoftDocs/partner-center-sdk#40]
On chapter https://docs.microsoft.com/en-us/partner-center/develop/create-azure-plan#lifecycle-management talking about Azure Plan lifecycle it is said "You can only suspend an existing Azure plan if it no longer has any active usage assets associated with it, including Azure usage subscriptions and Azure reservations."

But some information are missing on the lifecycle of the Azure Plan : 

1/ A client can only have 1 "Azure Plan" by Partner, if an "Azure Plan" is suspended/cancelled, it is not disapear (the azure plan still exist)

2/ because it is not disapear, it is not possible to create a "new" Azure Plan, because the previous one not yet disapear

3/ How many time it will be required to make disapear a "suspended" Azure Plan ? ie. if an Azure Plan is cancelled mid-Nov, does the plan will disapear after the end of biling cycle ? (ie. End-Nov + 2 days ? 

4/ If the "suspended" Azure Plan, not disapear by itself, how to make it disapear ? and be allowed to create a New Azure Plan ? Support Case ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d0ab6c9-e1b8-52bb-4aab-09d95927e7ca
* Version Independent ID: c3602d0b-ddd5-fea8-2179-8b35791f9cc9
* Content: [Create an Azure plan - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/create-azure-plan#feedback)
* Content Source: [develop/create-azure-plan.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/create-azure-plan.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-csp**
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by MaxHogervorst** [comment]
@lauradolan any updates on this?

**Comment by isaiahwilliams** [comment]
A partner will only create a single Azure Plan for a given customer. If the customer needs more than one Azure subscription that is done through the Azure Cost Management section of the Azure portal. Note you will access this using partner credentials.

Can you help us understand why you are looking for the Azure Plan to be removed so you can add a new one?

**Comment by JasonWHowell** [comment]
@MaxHogervorst Thanks for the question. Isaiah recently provided an answer, and I hope that resolves your question. We'll close the issue for now, but please let us know if you need additional clarification. Thanks! Jason
