### ISSUE TITLE
Onetime API?

### ISSUE THREAD

**Issue by rlisnoff** [MicrosoftDocs/partner-center-sdk#41]
In your document it says:
"Except for bug fixes, this API is no longer being updated. You should update your applications to call the onetime API instead of marketplace. The onetime API provides additional functionality, and will continue to be updated."

Where is the documentation for this Onetime API? Can we get a link in this document directing us to the new one?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 228ec42c-bda6-5d1d-aa73-891cb71aa153
* Version Independent ID: 2e430eda-4927-633b-eae7-c1932e4cb88c
* Content: [Get invoice line items - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/get-invoiceline-items?source=docs#feedback)
* Content Source: [develop/get-invoiceline-items.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/get-invoiceline-items.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-csp**
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by isaiahwilliams** [comment]
We have recently made an update to clarify this. It is the same documentation, what is being retired is the use of the value Marketplace. Going forward we recommend that you leverage the OneTime billing provider.

**Comment by jsjlewis96** [comment]
As of today (21/02/2020) it is still not clear that the OneTime api is in fact the API that the documentation is for. In fact until this point neither myself nor any of the rest of my team knew what the OneTime api was (despite using it), so perhaps there is an opportunity for some better messagin / brand awareness in the docs
