### ISSUE TITLE
How to enable subscription?

### ISSUE THREAD

**Issue by RobertHemsley** [MicrosoftDocs/partner-center-sdk#42]
This guide only outlines method via API's. How do you enable RI's on a subscription using partner center without API's?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 639479d8-b6b5-df55-8c01-d796aabd9f05
* Version Independent ID: b480f13d-f244-60ca-783d-41c1b69c942b
* Content: [Register a subscription - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/register-a-subscription)
* Content Source: [develop/register-a-subscription.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/register-a-subscription.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-csp**
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by isaiahwilliams** [comment]
This step outlined in this document is handled by the Partner Center dashboard. After you have purchased the the Reserved Instance it will automatically cover anything with it's scope and that matches what was purchased. As an example if your purchased a reservation for a customer for the B1s virtual machine and the scope of the reservation is set to shared, it will cover N B1s, were N is the number of units specified when you purchased the reservation. There are no actions that you need to take for it to apply.

**Comment by lauradolan** [comment]
Hi there, in addition, we also have the CSP documentation for RIs here: https://docs.microsoft.com/en-us/partner-center/azure-ri-server-subscriptions.
