### ISSUE TITLE
Partner means indirect provider or could be also indirect reseller?

### ISSUE THREAD

**Issue by wisterian** [MicrosoftDocs/partner-center-sdk#43]
PartnerId is the indirect provider ID or could refer to indirect reseller Id?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b592cc6-2c52-9a91-e5ef-77841c0cada0
* Version Independent ID: 9c73744d-d27c-817b-e942-98eafef4db33
* Content: [Utility resources - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/utility-resources#feedback)
* Content Source: [develop/utility-resources.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/utility-resources.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-csp**
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by vijvala** [comment]
@wisterian This a old issue, if you still have any open questions, please reach out to us on https://www.yammer.com/cloudpartnercommunity/#/threads/inGroup?type=in_group&feedId=6589502&view=all
