### ISSUE TITLE
Is Azure Plan reset when you remove customers?

### ISSUE THREAD

**Issue by slavizh** [MicrosoftDocs/partner-center-sdk#44]
Hi,
I have reached the limit of Azure plans that can be created. Because of that I have removed the customers for which I have created the Azure plans but still I cannot create new Azure Plans. Is this limit reset? If it is not reset how to proceed in such scenario. I need to test PowerShell script that creates customer, creates Azure Plan and creates Azure Plan subscriptions. I need to test that script from end to end to make sure it is working without any issues.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 212db5d1-1f37-9c2e-16b4-f8a24511f582
* Version Independent ID: 1de68d52-8775-232b-f533-a879a0dd7bbb
* Content: [Test and debug - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/test-and-debug)
* Content Source: [develop/test-and-debug.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/test-and-debug.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-csp**
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by vijvala** [comment]
@slavizh This is an old issue, If you are still looking for answers, please reach out on Yammer-  https://www.yammer.com/cloudpartnercommunity/#/threads/inGroup?type=in_group&feedId=6589502&view=all
