### ISSUE TITLE
Why do I have partially duplicate data in my audit records?

### ISSUE THREAD

**Issue by xdmushui** [MicrosoftDocs/partner-center-sdk#46]
Why do I have partially duplicate data in my audit records?
What causes this to happen? Is It Microsoft's own system, or is it our system?
![image](https://user-images.githubusercontent.com/3242057/70194694-3acac580-173e-11ea-858d-93e61d4d80cd.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e7f8130-90b6-4720-0b07-54ffe6355f59
* Version Independent ID: 8cc4cb78-8737-0456-7a5d-cf8d59d7b3e8
* Content: [Get a record of Partner Center activity - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/get-a-record-of-partner-center-activity-by-user#request)
* Content Source: [develop/get-a-record-of-partner-center-activity-by-user.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/get-a-record-of-partner-center-activity-by-user.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-csp**
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by isaiahwilliams** [comment]
I would recommend that you open a support ticket regarding this issue. That way our team can help investigate.

**Comment by JasonWHowell** [comment]
#please-close
