### ISSUE TITLE
Solution does not build

### ISSUE THREAD

**Issue by ajenns** [MicrosoftDocs/partner-center-sdk#48]
When following this step: Open, configure, and run:  PartnerConsent project found in the Partner-Center-DotNet-Samples\secure-app-model\keyvault directory. I get a reference error.  I have tried to fix the references using NuGet, but entered into reference hell.  I am not sure how to get the sample provided to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83b890e5-4406-2862-bcf3-cabd6e90d9cb
* Version Independent ID: 8383e9ca-8319-70a8-a32c-d03e63d5a1f9
* Content: [Partner Center authentication - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/partner-center-authentication?source=docs#feedback)
* Content Source: [develop/partner-center-authentication.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/partner-center-authentication.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-csp**
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by ajenns** [comment]
Sorry I meant the solution does not RUN.  it builds but gives errors trying to run it.

**Comment by isaiahwilliams** [comment]
@ajenns can you share the exact errors you are encountering?

**Comment by ajenns** [comment]
Sure, When I try to run the PartnerConsent application (with only app.config changes) I get this error: 
(Thrown on line 17 of Startup.cs)
System.IO.FileLoadException: 'Could not load file or assembly 'Microsoft.IdentityModel.Tokens, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'

**Comment by isaiahwilliams** [comment]
@ajenns thank you for sharing this information. A pull request has been created to address this issue. Once it is merged the issue will be resolved. You can see the purposed changes [here](https://github.com/microsoft/Partner-Center-DotNet-Samples/pull/46).

**Comment by isaiahwilliams** [comment]
@ajenns I have merged the changes required to address this issue. You should no longer encounter this error.
