### ISSUE TITLE
Missing steps

### ISSUE THREAD

**Issue by ajenns** [MicrosoftDocs/partner-center-sdk#51]
There are quite a few missing steps from this page.  Initial steps for instance.  You cannot follow the instructions because quite a few steps are missing and even incorrect.  For steps 2 and 3 the provided steps don't make sense as they are missing 3 or 4 steps in between, and even then they are still giving incorrect information. This page does not give a working solution/example.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83b890e5-4406-2862-bcf3-cabd6e90d9cb
* Version Independent ID: 8383e9ca-8319-70a8-a32c-d03e63d5a1f9
* Content: [Partner Center authentication - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/partner-center-authentication?source=docs)
* Content Source: [develop/partner-center-authentication.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/partner-center-authentication.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-csp**
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by isaiahwilliams** [comment]
@ajenns can you clarify what section of the documentation are referencing? I have created a request to update a subsection of the document, so this might be something that will be addressed in the coming days.
