### ISSUE TITLE
Unable to sign in

### ISSUE THREAD

**Issue by BukeMan** [MicrosoftDocs/partner-center-sdk#52]
After entering my credentials on a sign-in page I get the following error:
AADSTS500119: Redirect URIs with urn: schemes are prohibited. Use a different scheme, or https://login.microsoftonline.com/common/oauth2/nativeclient

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83b890e5-4406-2862-bcf3-cabd6e90d9cb
* Version Independent ID: 8383e9ca-8319-70a8-a32c-d03e63d5a1f9
* Content: [Partner Center authentication - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/partner-center-authentication#feedback)
* Content Source: [develop/partner-center-authentication.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/partner-center-authentication.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-csp**
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by BukeMan** [comment]
My fault. I forgot to add localhost as redirect URI

**Comment by wasife** [comment]
Hello, How did you add the redirect URL? 
I am using Partner Center web app to generate the Refresh token. I have created the web app and using its Id and the secret. It worked fine until short while ago, but now suddenly it shows the above error message that you posted.

Any help will be greatly appreciated.

Regards,
