### ISSUE TITLE
Rate Card API: Offer Type Not Valid

### ISSUE THREAD

**Issue by jeryanders** [MicrosoftDocs/partner-center-sdk#54]
Hello!

I'm working on integrating with the latest prices via the Rate Card API detailed [here](https://docs.microsoft.com/en-us/partner-center/develop/get-prices-for-microsoft-azure); however, I'm running into issues when following the documentation. When making the request below, the API responds with "Offer type not valid," but nowhere in the docs is this mentioned. Please update them with information on how to set the offer type.

Request:
```
{
   method: 'GET',
   uri: 'https://api.partnercenter.microsoft.com/v1/ratecards/azure&currency=USD&region=US'
}
```

Platform: node
Library used: node-fetch

Best,
Jesse

**Comment by isaiahwilliams** [comment]
@jeryanders this is an interesting error, and I am not sure what exactly might be causing it. Through my testing this morning it does not appear that it can be reproduced with my test environment. Using the Partner Center PowerShell module I made the following request 

PowerShell
```powershell
Get-PartnerAzureRateCard -Currency USD -Region US -Debug
```

REST
```http
https://api.partnercenter.microsoft.com/v1/ratecards/azure?currency=USD&region=US 
```

Would you be able to test again this morning to see if everything is working?

**Comment by jeryanders** [comment]
@isaiahwilliams My apologies for the delay. We are currently in the process of scoping out this work, and I'm running a bit behind on getting back to you. I'll hopefully get the time before the end of the week to try this again.

**Comment by JasonWHowell** [comment]
@jeryanders We recently provided an answer, and I hope that resolves your question. We'll close the issue for now, but please let us know if you need additional clarification in the future. Thanks! Jason
