### ISSUE TITLE
OneTimeInvoiceLineItem and DailyRatedUsageLineItem descriptions do not match JSON payload

### ISSUE THREAD

**Issue by Woody1193** [MicrosoftDocs/partner-center-sdk#55]
The fields described in the `OneTimeInvoiceLineItem` and `DailyRatedUsageLineItem` descriptions do not match the JSON payloads that will actually be received when requesting these items from the API. See https://docs.microsoft.com/en-us/partner-center/develop/get-invoiceline-items as a reference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e78c2c38-25f1-35f6-70ff-8626384c8ee5
* Version Independent ID: e4e645c5-45ab-11b3-ace9-1d73aba4d665
* Content: [Invoice resources - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/invoice-resources#feedback)
* Content Source: [develop/invoice-resources.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/invoice-resources.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-csp**
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by vijvala** [comment]
@Woody1193 If you still have questions please reach out to us on Yammer -https://www.yammer.com/cloudpartnercommunity/#/threads/inGroup?type=in_group&feedId=6589502&view=all 

Also please add details on which fields to be specific.
