### ISSUE TITLE
Typo in Customer resource description.

### ISSUE THREAD

**Issue by mediteck** [MicrosoftDocs/partner-center-sdk#56]
The line 'Most broadly, a customer resouce can be any person, employee, ' contains a typo where the word 'resource' is spelled wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05bb17fe-f822-6544-f196-204171b55ca3
* Version Independent ID: e7994d0c-14e5-6283-520f-d4a42993fed0
* Content: [Customer resources - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/customer-resources#feedback)
* Content Source: [develop/customer-resources.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/customer-resources.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-csp**
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by lauradolan** [comment]
Thanks! We'll update that.
