### ISSUE TITLE
Azure Plan subscrptions

### ISSUE THREAD

**Issue by JamesMinton** [MicrosoftDocs/partner-center-sdk#57]
Hello,

Is anyone able to tell me how I'd be able to get the Subscriptions "underneath" an Azure Plan Subscription with an SDK call?
I've tried getting all Subscriptions for the customer, as well as trying to get all entitlements. But no joy. 
Any help would be greatly appreciated

![AzurePlanexample](https://user-images.githubusercontent.com/57450864/72142878-94ea2680-338d-11ea-95ce-ca522033de22.PNG)

Kind Regards, 
James

**Comment by isaiahwilliams** [comment]
@JamesMinton you will want to leverage the [Azure entitlements](https://docs.microsoft.com/partner-center/develop/get-a-list-of-azure-entitlements-for-subscription) to get this information.

**Comment by JasonWHowell** [comment]
@JamesMinton Thanks for the question. Isaiah recently provided an answer, and I hope that resolves your question. We'll close the issue for now, but please let us know if you need additional clarification. Thanks! Jason
