### ISSUE TITLE
The code under "Get refresh token" gave me an access token.

### ISSUE THREAD

**Issue by degrover-cn** [MicrosoftDocs/partner-center-sdk#60]
Using the authorization code from "Get authorization code" and following the steps under "Get refresh token"  got me a token that failed to work as a refresh token for "Get access token" but that worked fine used directly as a bearer token for the CSP API, i.e. used directly in "Make Partner Center API calls". The token from the "Get refresh token" sample also had only one hour time to live.

Please advise. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad81757a-da98-492e-aa46-cd920709432e
* Version Independent ID: fbf50fa1-8698-5e30-483b-2408426d349d
* Content: [Enable secure application model - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/enable-secure-app-model?cr_cc=WPGM_PRM_GL_NN_TR_NN_OO_EM_secure_application&mkt_tok=eyJpIjoiTlRKbU1XTm1PR1ZtTUdNeiIsInQiOiJHSzlBNldmaFlVS1k0Q3hYZDMrNzVLMlpCdmZjVGE3RVpwdWJ5VUJhZDRFb0V1azRnUUJUdnFocWVvaWZkRlN1RnZpcEUxeFhUREdFQkZHYlIzOWdJVllmVFI0WkNDeFBDdDRvcVFCeUF5UEtFdmZLZTFsY1RyYlRETWY0elNhSiJ9#feedback)
* Content Source: [develop/enable-secure-app-model.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/enable-secure-app-model.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-csp**
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by isaiahwilliams** [comment]
@degrover-cn when you perform the authorization code exchange Azure Active Directory will return a handful of items including a resource token. You will want to make sure that you secure store the refresh token and then use that to request new access tokens. An access token will only ever be valid for a hour, so if you have a long running operation you will need to request a new access token to avoid any impact. 

I am exactly sure what issues you are encountering. Can you provide additional details to help us understand if you are having issues due to using an access token instead a refresh token?

**Comment by degrover-cn** [comment]
According to the documentation what I wanted to pass to the next call was the “code” value

Log in to Azure AD at the following URL: https://login.microsoftonline.com/common/oauth2/authorize?client_id=Application-Id&response_mode=form_post&response_type=code%20id_token&scope=openid%20profile. Be sure to log in with the user account from which you will make Partner Center API calls (such as an admin agent or sales agent account).

code=AuthorizationCodeValue&

then POST https://login.microsoftonline.com/CSPTenantID/oauth2/token

resource=https%3a%2f%2fapi.partnercenter.microsoft.com&client_id=Application-Id&client_secret=Application-Secret&grant_type=authorization_code&code=AuthorizationCodeValue

That returns a bearer token. Your sample response body even shows it that way, as a bearer token with an hour to live.

The token causes an error if I follow the next step

POST https://login.microsoftonline.com/CSPTenantID/oauth2/token HTTP/1.1<https://login.microsoftonline.com/CSPTenantID/oauth2/token%20HTTP/1.1>

resource=https%3a%2f%2fapi.partnercenter.microsoft.com&client_id=Application-Id &client_secret= Application-Secret&grant_type=refresh_token&refresh_token=RefreshTokenVlaue&scope=openid

but works as a bearer token against the CSP API

**Comment by degrover-cn** [comment]
Please look at the response body you show for the "refresh token" call. Your object isn't complete. I modeled from that to get an object to deserialize and kissed fields you omitted.

**Comment by vijvala** [comment]
@degrover-cn If you still have questions, please reach us on the Yammer - https://www.yammer.com/cloudpartnercommunity/#/threads/inGroup?type=in_group&feedId=6589502&view=all
