### ISSUE TITLE
0145P vs AzurePlan SKU Availability Query

### ISSUE THREAD

**Issue by JoeBrockhaus** [MicrosoftDocs/partner-center-sdk#61]
In the code section below: 

```c#
// Get the availabilities for an Azure reservation product and sku which are applicable to Microsoft Azure (MS-AZR-0145P) subscriptions only.
var availabilities = partnerOperations.Products.ByCountry(countryCode).ById(productIdForAzureReservation).Skus.ById(skuIdForAzureReservation).Availabilities.ByReservationScope("AzurePlan").Get();
```

Is the parameter for `ByReservationScope` correct? Should it really be `AzurePlan` for the 0145P Offer?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f09e84e-9954-04a7-9657-9702602882f0
* Version Independent ID: 6ccf1be2-1748-5b7e-1273-4a03d4041341
* Content: [Get a list of availabilities for a SKU (by country) - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/get-a-list-of-availabilities-for-a-sku)
* Content Source: [develop/get-a-list-of-availabilities-for-a-sku.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/get-a-list-of-availabilities-for-a-sku.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-csp**
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by JasonWHowell** [comment]
@JoeBrockhaus Thanks for the question. I understand that the question was answered offline. We'll close the issue for now, but please let us know if you need additional clarification. Thanks! Jason
