### ISSUE TITLE
Only App Authentication also works

### ISSUE THREAD

**Issue by xxankitxx** [MicrosoftDocs/partner-center-sdk#62]
Incorrect Authentication mentioned on this page. Only App Authentication also works

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffcb4bc8-dcb4-bbf4-b894-ca23fde08953
* Version Independent ID: 6e6a2dcc-0547-3018-816d-816513c94583
* Content: [Get confirmation of customer acceptance of Microsoft Customer Agreement - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/get-confirmation-of-customer-agreement)
* Content Source: [develop/get-confirmation-of-customer-agreement.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/get-confirmation-of-customer-agreement.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-csp**
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by vijvala** [comment]
@xxankitxx If you still have questions, please reach us on the Yammer - https://www.yammer.com/cloudpartnercommunity/#/threads/inGroup?type=in_group&feedId=6589502&view=all
