### ISSUE TITLE
Error handling and corner cases

### ISSUE THREAD

**Issue by evilguest** [MicrosoftDocs/partner-center-sdk#63]
1. What if I have an order with two line items referencing the same offer ID (e.g. for 5 and 10 units, respectively). Which one is going to be cancelled by the partial cancellation request?
2. Is the cancellation idempotent? I.e. what status would be returned upon an attempt to cancel an already cancelled item/order - 200, 409, etc?
2.1. Does this depend on the MS-RequestID values to be the same?
3. What error codes, if any, would be returned in case the cancellation of any items fails? I mean both HTTP status and the error code specified in the payload.
4. What are the "normal" reasons for the cancellation request to be rejected? I.e. attempt after the cancellation window  is one of those. Is there any other possible reasons we should be ready to (so we display a correct UI to the end-user)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 717d1070-32dc-0343-ecc5-98a25800a31f
* Version Independent ID: beaf99ee-cd91-d000-2613-fbeb3c9f3c96
* Content: [Cancel software purchases - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/cancel-software-purchases#feedback)
* Content Source: [develop/cancel-software-purchases.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/cancel-software-purchases.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-csp**
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by vijvala** [comment]
1. It will cancel the entire Order.
2. Cancellation is idempotent. Will returned the cancelled object response. Will return 200.
2.1. For cancellation case you can provide any request ID .Ideally PC API honor idempotency as long as request ID and payload are same. 
3. We are working on API specific error codes. 
4. If you are cancelling within the airline policy it is allowed and outside of the window it is not allowed. 

@evilguest If you still need further assistance, please reachout to PC Support team
