### ISSUE TITLE
Get-AzureADApplication -Filter not working

### ISSUE THREAD

**Issue by LucasUCaaS** [MicrosoftDocs/partner-center-sdk#64]
Under App + User authentication > .NET (app+user authentication) > Grant the newly create Azure AD application the read secrets permissions using the Azure management portal or the following commands.

Is giving errors. I used my own app ID
Under App + User authentication > .NET (app+user authentication) > Grant the newly create Azure AD application the read secrets permissions using the Azure management portal or the following commands.

Is giving errors. I used my own app ID
$app = Get-AzureADApplication -Filter {AppId -eq '*******-***-****-****-************'}

Get-AzureADApplication : Cannot evaluate parameter 'Filter' because its argument is specified as a script block and there is no input. A script block cannot be evaluated without input.
At line:1 char:39
+ ... DApplication -Filter {AppId -eq *******-***-****-****-************}
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (:) [Get-AzureADApplication], ParameterBindingException
    + FullyQualifiedErrorId : ScriptBlockArgumentNoInput,Microsoft.Open.AzureAD16.PowerShell.GetApplication

**Comment by isaiahwilliams** [comment]
I would recommend that you ensure you are using the latest version of PowerShell. If you are still having issue you can leverage the other parameters available for the command. You can find the documentation at https://docs.microsoft.com/en-us/powershell/module/azuread/get-azureadserviceprincipal?view=azureadps-2.0

**Comment by JasonWHowell** [comment]
@LucasUCaaS Thanks for the question, and sorry for the delay in responded. Isaiah recently provided an answer, and I hope that resolves your question. We'll close the issue for now, but please let us know if you need additional clarification. Thanks! Jason
