### ISSUE TITLE
Misleading documentation about cancel subscription

### ISSUE THREAD

**Issue by s-krawczyk** [MicrosoftDocs/partner-center-sdk#65]
Please take a look into issue that is really related to this documentation [here](https://github.com/MicrosoftDocs/partner-center-sdk/issues/66#issue-557975880)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abab82ad-1bb6-7bdd-1cf7-08bf4284d86b
* Version Independent ID: 18ff89b0-c204-9b6f-c5bb-3cd42a68eef1
* Content: [Cancel a commercial marketplace subscription - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/cancel-an-azure-marketplace-subscription)
* Content Source: [develop/cancel-an-azure-marketplace-subscription.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/cancel-an-azure-marketplace-subscription.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-csp**
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by vijvala** [comment]
@s-krawczyk This is an old issue and we do have a concept of cancel subscription. Please communicate on Yammer where you will find quick responses.  https://www.yammer.com/cloudpartnercommunity/#/threads/inGroup?type=in_group&feedId=6589502&view=all
