### ISSUE TITLE
Misleading documentation

### ISSUE THREAD

**Issue by s-krawczyk** [MicrosoftDocs/partner-center-sdk#66]
Look at this quote and focus on word **canceled**: 

> The number of subscriptions that can exist on the customer tenant at a given time, this includes subscriptions that are active or **canceled**.

I was trying to fin out what means "cancel". There is no such status on subscription. We have active, none, suspended, deleted. In next step what I found is there is page case how to "cancel" the subscription [(link)](https://docs.microsoft.com/en-us/partner-center/develop/cancel-an-azure-marketplace-subscription). What they say there is status should be set to "deleted". Such scenario is also available in samples sdk project.

![image](https://user-images.githubusercontent.com/9395791/73522035-d0fe2d80-4407-11ea-8630-ac0da7812648.png)

 What I did is to execute it on our PN account. In result I got error that such operation is not possible.

![image](https://user-images.githubusercontent.com/9395791/73522118-f8ed9100-4407-11ea-9f4a-319716712436.png)

Expectation is that you update both documents that no one else will waste time to investigate such inconsistencies.
First document should be updated because there is no such status like canceled etc.
Second document should be updated because of two reasons:
1. There is no possibility to "cancel" subscription form UI
2. There is no possibility to set status to "deleted" from sample, API etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13d40442-5acc-1f42-bc7c-10754b4f10df
* Version Independent ID: 8cb3bcb8-7e08-279d-a5ab-4f98e00d63f9
* Content: [Offer resources - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/offer-resources)
* Content Source: [develop/offer-resources.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/offer-resources.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-csp**
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by vijvala** [comment]
@s-krawczyk This is an old issue and we do have a concept of cancel subscription. Please communicate on Yammer where you will find quick responses.  https://www.yammer.com/cloudpartnercommunity/#/threads/inGroup?type=in_group&feedId=6589502&view=all

**Comment by vijvala** [comment]
Internal Link for tracking --> Closing this issue, communication will be handled on Yammer. 
https://microsoft.visualstudio.com/OSGS/_workitems/edit/27860669
