### ISSUE TITLE
Erors code inventory

### ISSUE THREAD

**Issue by EricLacroix** [MicrosoftDocs/partner-center-sdk#67]
Team where are the list of exhaustive  error code like understood that those are http status code : 
Indirect Reseller hasn't signed MPA: MPANotAcceptedByIndirectReseller = 900123
Transacting partner hasn't signed MPA: MPANotAcceptedByPartner = 900124

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2fe152a-6997-0fe5-b901-c2927b1f1345
* Version Independent ID: 9335a976-dfdf-ac72-e913-eeae86fb6085
* Content: [Partner Center REST error codes - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/error-codes)
* Content Source: [develop/error-codes.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/error-codes.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-csp**
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by vijvala** [comment]
I will be closing this as we created an internal ticket to track the status and will notify once the error code documentation is updated. 
https://microsoft.visualstudio.com/OSGS/_workitems/edit/26590933
