### ISSUE TITLE
Reservation type missing term and billingPlan fields

### ISSUE THREAD

**Issue by Woody1193** [MicrosoftDocs/partner-center-sdk#69]
The type description for `Reservation` is missing the `term` and `billingPlan` fields.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ffaf0a7-083d-5c64-0f11-a6a57eea6323
* Version Independent ID: 72f48f7d-b3c3-ebb5-34df-01946ac3bc50
* Content: [Entitlement resources - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/entitlement-resources#artifact)
* Content Source: [develop/entitlement-resources.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/entitlement-resources.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-csp**
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by vijvala** [comment]
@Woody1193 Please open support ticket with clear information on what is missing and which API you are referring. Closing this ticket as you will need to create CS support ticket. https://docs.microsoft.com/en-us/partner-center/report-problems-with-partner-center
