### ISSUE TITLE
Changes to licenses quantity not applied immediately

### ISSUE THREAD

**Issue by djmrky** [MicrosoftDocs/partner-center-sdk#72]
When using the C# code from above, the license quantity is not updated immediately after this code. If we try to assign this license after increment, it's not working (the error is that there are no available licenses), but if I try assigning after some time (20-40 seconds), it actually works. This makes the whole process really unreliable. 
We've implemented the solution where we query the number of available licenses (after increment) until we get a correct number of licenses (this is confirmed after 20-40 seconds) and then we assign licenses.
This is causing major problems with our workflow for licenses.

Is there any better and more reliable way to work with licenses in partner center?

But even this way started working wrong and we get an error message that there are not enough licenses after it is confirmed that there are. It's like the real number of licenses is updated even later than before.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e357d60-0328-0d63-27d3-bbbe67b3fcb1
* Version Independent ID: fc98ee06-f930-14fc-1f1f-94610759272f
* Content: [Change the quantity of a subscription - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/change-the-quantity-of-a-subscription#feedback)
* Content Source: [develop/change-the-quantity-of-a-subscription.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/change-the-quantity-of-a-subscription.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-csp**
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by vijvala** [comment]
@djmrky  Are you still facing this issue? If so can you please point me to the API doc page that you are having issues? I will be closing this issue so we can track the conversation on Yammer. If this is still an open issue, i would like you to raise a support ticket and we can follow-up from there.
