### ISSUE TITLE
What scenario should use by country and what scenario should use by customer

### ISSUE THREAD

**Issue by xdmushui** [MicrosoftDocs/partner-center-sdk#73]
How to choose?
What scenario should use by country and what scenario should use by customer?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2050ddb5-b883-99bd-1c84-fe59551f3a19
* Version Independent ID: 1300f29d-0e24-ff7d-2c27-de0ea7f33e6b
* Content: [Get a list of availabilities for a SKU (by customer) - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/get-a-list-of-availabilities-for-a-sku-by-customer?source=docs#feedback)
* Content Source: [develop/get-a-list-of-availabilities-for-a-sku-by-customer.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/get-a-list-of-availabilities-for-a-sku-by-customer.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-csp**
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by vijvala** [comment]
@xdmushui It will be great if you can use Yammer https://www.yammer.com/cloudpartnercommunity/#/threads/inGroup?type=in_group&feedId=6589502 for asking any future question on this. Also please provide context on what you would like to address.

**Comment by xdmushui** [comment]
> @xdmushui It will be great if you can use Yammer https://www.yammer.com/cloudpartnercommunity/#/threads/inGroup?type=in_group&feedId=6589502 for asking any future question on this. Also please provide context on what you would like to address.

 I sent this question: https://www.yammer.com/cloudpartnercommunity/#/Threads/show?threadId=798993187430400
Thank you.
