### ISSUE TITLE
not working for me

### ISSUE THREAD

**Issue by degrover-cn** [MicrosoftDocs/partner-center-sdk#74]
We have a tool our CSP tenants can use to add licenses.

I have a service user, we use App+User for the service user as newly required by 

https://docs.microsoft.com/en-us/partner-center/develop/enable-secure-app-model

Working on code to check for the new agreement, upgraded from 1.09 to 1.15 to get the ByAgreementType method.

IAggregatePartner partner = GetUserPartnerOperations();

var icust = partner.Customers.ById(tenantId);

var agreements = icust.Agreements.ByAgreementType("MicrosoftCustomerAgreement").Get();

I call this for a tenant I KNOW has a completed agreement because they have updated licenses within the past week; however, the code above returns an empty collection. Please advise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffcb4bc8-dcb4-bbf4-b894-ca23fde08953
* Version Independent ID: 6e6a2dcc-0547-3018-816d-816513c94583
* Content: [Get confirmation of customer acceptance of Microsoft Customer Agreement - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/get-confirmation-of-customer-agreement#feedback)
* Content Source: [develop/get-confirmation-of-customer-agreement.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/get-confirmation-of-customer-agreement.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-csp**
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by degrover-cn** [comment]
"MicrosoftCloudAgreement" works but gets their 2018 agreement.

**Comment by vijvala** [comment]
@degrover-cn If you are still facing this issue, I would suggest you can open a support ticket with Partner Center. Or you can use Yammer for communication -https://www.yammer.com/cloudpartnercommunity/#/threads/inGroup?type=in_group&feedId=6589502
