### ISSUE TITLE
Error 404 appears

### ISSUE THREAD

**Issue by dei79** [MicrosoftDocs/partner-center-sdk#75]
Hello,

I tried to call the REST api, it ends up with an error 404 all the team. When I do this for the unbilled consumption it works like charme.

Regards
Dirk 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77bf0277-93cf-87cd-3b38-dd991bca0040
* Version Independent ID: 5366c095-637c-770b-27c3-5a7850833180
* Content: [Get invoice billed commercial consumption line items - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/get-invoice-billed-consumption-lineitems)
* Content Source: [develop/get-invoice-billed-consumption-lineitems.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/get-invoice-billed-consumption-lineitems.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-csp**
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @JasonWHowell
* Microsoft Alias: **jasonh**

**Comment by vijvala** [comment]
@dei79 I am not sure if you still need help on this. If so please open a support ticket to get your questions answered. Or you can use Yammer for asking questions and we can direct your query.
https://www.yammer.com/cloudpartnercommunity/#/threads/inGroup?type=in_group&feedId=6589502
