### ISSUE TITLE
It supports App-only authentication

### ISSUE THREAD

**Issue by xxankitxx** [MicrosoftDocs/partner-center-sdk#76]
When will this page be updated? This operation supports App-only authentication since last two months and no update has still been made to this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92778f22-8aa2-7ae6-45ad-10ab80de93cb
* Version Independent ID: 75280033-0b5b-f0b7-7c02-ae497ac90beb
* Content: [Update a customer's billing profile - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/update-a-customer-s-billing-profile)
* Content Source: [develop/update-a-customer-s-billing-profile.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/update-a-customer-s-billing-profile.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-csp**
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @JasonWHowell
* Microsoft Alias: **jasonh**

**Comment by JasonWHowell** [comment]
Hi @xxankitxx,
Thanks for asking about it. We updated it today. 
https://github.com/MicrosoftDocs/partner-center-sdk/pull/80
I'll close out the issue now.  Thanks, Jason
