### ISSUE TITLE
[CountryValidationRules] Add "sample" fields for postal code and phone number

### ISSUE THREAD

**Issue by ymilin** [MicrosoftDocs/partner-center-sdk#77]
Hi,

It would be very useful for the `postalCode` and `phoneNumber` `Address` Fields to have 
a corresponding Sample/Format Field, like we already have with `taxId` (`taxIdFormat` and `taxIdSample`) 

It would allow Partners to improve the user experience with placeholders and useful validation messages.

In our experience, the Address Validation request is not very useful in this regard as it:
- does not validate phone numbers
- does not return useful error messages
- is too slow to be used as a synchronous call in interface (at least in Europe for us).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87c8eccc-cf28-68ce-85a1-c3df9fe8df87
* Version Independent ID: 29bd2977-f9cf-95fe-8b12-48465a3c7d00
* Content: [Get address formatting rules by market - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/get-market-specific-validation-data)
* Content Source: [develop/get-market-specific-validation-data.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/get-market-specific-validation-data.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-csp**
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @JasonWHowell
* Microsoft Alias: **jasonh**

**Comment by vijvala** [comment]
@ymilin  I Would like to understand your question in more detail but this is not the right source of communication. It will be great if you can start the yammer thread and we can respond on that or invite other teams as needed. Please state the problem you are facing and the scenario you are trying to address. A sample request and response will be helpful. https://www.yammer.com/cloudpartnercommunity/#/threads/inGroup?type=in_group&feedId=6589502
