### ISSUE TITLE
"Term Duration" field should be omitted from sample code

### ISSUE THREAD

**Issue by jhoak** [MicrosoftDocs/partner-center-sdk#81]
When partners try to use the listed C# sample code to provision Azure Plan via the Partner Center APIs, they run into errors unless TermDuration is omitted. This has led to some frustration and partner escalations. We should get rid of the advice to include a term duration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f0052f0-94cf-632b-335a-ac611234923a
* Version Independent ID: cf973482-e47f-f1bc-7824-12107adf8840
* Content: [Create a cart - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/create-a-cart)
* Content Source: [develop/create-a-cart.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/create-a-cart.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-sdk**
* GitHub Login: @JasonWHowell
* Microsoft Alias: **jasonh**

**Comment by vijvala** [comment]
Internally tracking this -https://microsoft.visualstudio.com/OSGS/_workitems/edit/28174953
