### ISSUE TITLE
Account not found

### ISSUE THREAD

**Issue by KevinBurton** [MicrosoftDocs/partner-center-sdk#82]
I am getting a message the account with could not be found (52005). This account does exist as it shows up in the response to /v1/customers?size=40. So I am not clear what it means that the account could not be found?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b552457-2483-fedf-6e92-2e11b7a33825
* Version Independent ID: 9158d8d1-d358-aa0b-0f51-149b66532899
* Content: [Verify an indirect reseller's Microsoft Partner Agreement signing status - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/verify-indirect-reseller-mpa-status#feedback)
* Content Source: [develop/verify-indirect-reseller-mpa-status.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/verify-indirect-reseller-mpa-status.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-sdk**
* GitHub Login: @JasonWHowell
* Microsoft Alias: **jasonh**

**Comment by JasonWHowell** [comment]
Sorry, we are slow to monitor and reply here. Consider asking the question in the Q&A forum. https://docs.microsoft.com/en-us/answers/topics/partner-center-api.html

**Comment by vijvala** [comment]
@KevinBurton  https://docs.microsoft.com/en-us/partner-center/report-problems-with-partner-center

Please follow the direction on opening a CS support ticket to address your questions.
