### ISSUE TITLE
Combine multiple queries?

### ISSUE THREAD

**Issue by KevinBurton** [MicrosoftDocs/partner-center-sdk#83]
How do I combine queries so that it would for a query for A AND B. Where A is like the query on this page and B would be like this query but on a different field?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c46bf963-bc90-0332-a89a-34d6933f7c1b
* Version Independent ID: 4cc6dbca-9e03-2882-ca30-556d6fbd4425
* Content: [Get a list of customers filtered by a search field - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/get-a-customer-by-name)
* Content Source: [develop/get-a-customer-by-name.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/get-a-customer-by-name.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-sdk**
* GitHub Login: @JasonWHowell
* Microsoft Alias: **jasonh**

**Comment by JasonWHowell** [comment]
Sorry, we are slow to monitor and reply here. Consider asking the question in the Q&A forum. https://docs.microsoft.com/en-us/answers/topics/partner-center-api.html

**Comment by vijvala** [comment]
@KevinBurton  Not enough details and as mentioned in other ticket

 https://docs.microsoft.com/en-us/partner-center/report-problems-with-partner-center

Please follow the direction on opening a CS support ticket to address your questions.
