### ISSUE TITLE
Always getting BadRequest exception

### ISSUE THREAD

**Issue by KevinBurton** [MicrosoftDocs/partner-center-sdk#85]
It seems that no matter what domain string I supply I get a BadRequest exception from the SDK call and a 404 from the REST call. What is the format for the domain name? What are some domain names that show an example of positive and negative responses? The specific API call is /v1/domains/<<domain>> or .Domains.ByDomain(domain).ExistsAsync() when using the SDK.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 718d860f-3e57-761e-46d1-77d5eaf69c1b
* Version Independent ID: 638b7c2c-29d2-f5be-e9d7-2992a2d3220b
* Content: [Verify domain availability - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/verify-domain-availability)
* Content Source: [develop/verify-domain-availability.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/verify-domain-availability.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-sdk**
* GitHub Login: @JasonWHowell
* Microsoft Alias: **jasonh**

**Comment by KevinBurton** [comment]
This is a PartnerException with a message of "Bad request" from the SDK.

**Comment by vijvala** [comment]
@KevinBurton  Please open a support ticket if you are still facing this issue. Unfortunately this is not a communication channel for us to followup. Please use Yammer or contact support for any additional questions. https://www.yammer.com/cloudpartnercommunity/#/threads/inGroup?type=in_group&feedId=6589502
