### ISSUE TITLE
Time to reflect the nickname change

### ISSUE THREAD

**Issue by brunosilva311** [MicrosoftDocs/partner-center-sdk#87]
Hi team, 
How long does it take for the subscription nickname change to reflect in the subscription in Azure Portal?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c7fff3e-2f6a-a07d-bba2-e1a01b93a46a
* Version Independent ID: 52712040-3f29-41a8-71e2-10306d767872
* Content: [Update the nickname for a subscription - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/update-the-nickname-for-a-subscription#feedback)
* Content Source: [develop/update-the-nickname-for-a-subscription.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/update-the-nickname-for-a-subscription.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-sdk**
* GitHub Login: @JasonWHowell
* Microsoft Alias: **jasonh**

**Comment by JasonWHowell** [comment]
Sorry, we are slow to monitor and reply here. Consider asking the question in the Q&A forum. https://docs.microsoft.com/en-us/answers/topics/partner-center-api.html

**Comment by vijvala** [comment]
@brunosilva311 
Please follow the direction on opening a CS support ticket to address your questions.
 https://docs.microsoft.com/en-us/partner-center/report-problems-with-partner-center

-
