### ISSUE TITLE
Invalid JSON in response example

### ISSUE THREAD

**Issue by BukeMan** [MicrosoftDocs/partner-center-sdk#88]
Response example is missing a closing curly brace '}'  inside lineItems property.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e699fea-8dd1-5e41-b53d-b14d6db2738b
* Version Independent ID: 325ed4a5-deff-30ab-85bb-711e9789dfc5
* Content: [Create an order - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/create-an-order?source=docs)
* Content Source: [develop/create-an-order.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/create-an-order.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-sdk**
* GitHub Login: @JasonWHowell
* Microsoft Alias: **jasonh**

**Comment by JasonWHowell** [comment]
Thanks @BukeMan I've fixed it and published. 

Next time, if you are willing, feel free to click Edit and edit the page in the github markdown editor (in the browser), and we'll review the change. Thanks, Jason
