### ISSUE TITLE
Documentation is inaccurate

### ISSUE THREAD

**Issue by Woody1193** [MicrosoftDocs/partner-center-sdk#89]
The link titled `Get all monthly usage records for a subscription` does not apply to Azure plans. Attempting to request from this link for an account associated with an Azure plan will result in a 400 error. Please update your documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d0ab6c9-e1b8-52bb-4aab-09d95927e7ca
* Version Independent ID: c3602d0b-ddd5-fea8-2179-8b35791f9cc9
* Content: [Create an Azure plan - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/create-azure-plan)
* Content Source: [develop/create-azure-plan.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/create-azure-plan.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-sdk**
* GitHub Login: @JasonWHowell
* Microsoft Alias: **jasonh**

**Comment by JasonWHowell** [comment]
Thanks @Woody1193 We'll take a look.
