### ISSUE TITLE
v 1.10.0 SDK Change Billing Cycle

### ISSUE THREAD

**Issue by DaraOladapo** [MicrosoftDocs/partner-center-sdk#9]
I get this error
Error	CS1061	'IOrderCollection' does not contain a definition for 'Patch' and no accessible extension method 'Patch' accepting a first argument of type 'IOrderCollection' could be found (are you missing a using directive or an assembly reference?)
for this code
var createdOrder = partnerOperations.Customers.ById(customerId).Orders.Patch(order);
docs link: https://docs.microsoft.com/en-us/partner-center/develop/change-the-billing-cycle

**Comment by DaraOladapo** [comment]
![image](https://user-images.githubusercontent.com/4347646/48377207-77f48d80-e6cd-11e8-8aec-97220d1c31ec.png)

**Comment by DaraOladapo** [comment]
![image](https://user-images.githubusercontent.com/4347646/48517952-495eea00-e868-11e8-8ace-53e087c855b0.png)
But the documentation says this.
I can successfully create order. but to update the billing cycle is what I have a problem with.

**Comment by isaiahwilliams** [comment]
Hi @DaraOladapo, 

Thank you for bring this issue to our attention. The line of code should look like the following 

```csharp
var createdOrder = partnerOperations.Customers.ById(customerId).Orders.ById(orderId).Patch(order);
```

Please let me know if you have any concerns or questions. 

@Xansky I will get this corrected a little later today.

**Comment by DaraOladapo** [comment]
It works now.
thank you.
