### ISSUE TITLE
Incorrect URL in the example

### ISSUE THREAD

**Issue by spiroszaf** [MicrosoftDocs/partner-center-sdk#90]
The example's URL should end with "https://api.partnercenter.microsoft.com/v1/productupgrades/eligibility". (I missed the syntax's URL and used the example's URL and accidentally had me trigger an upgrade!)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf00f4f8-c9b0-3660-2f9d-3ae1d6840dd2
* Version Independent ID: d49d79c2-e7cb-72eb-f74b-185b252bdf98
* Content: [Check a customer's eligibility for upgrading to an Azure plan - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/get-eligibility-for-product-upgrade#feedback)
* Content Source: [develop/get-eligibility-for-product-upgrade.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/get-eligibility-for-product-upgrade.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-sdk**
* GitHub Login: @JasonWHowell
* Microsoft Alias: **jasonh**

**Comment by JasonWHowell** [comment]
@spiroszaf  Thanks for pointing that REST example.

We'll take a look and adjust the article soon. Thanks, Jason
