### ISSUE TITLE
Zero-width non breaking space

### ISSUE THREAD

**Issue by cf-jola** [MicrosoftDocs/partner-center-sdk#91]
Hi

I was having some issues parsing the json result from the API endpoint when I noticed there's a "ZERO WIDTH NO-BREAK SPACE" returned at the beginning, as you can see in the example here: https://qaz.wtf/u/show.cgi?show=%22%EF%BB%BF%7B%5C%22isSigned%5C%22%3Afalse%7D%22&type=string 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3eb021e3-195e-6c4c-e7e1-16b30a0ff700
* Version Independent ID: e042b366-43e2-aad1-d098-af0ec7c825eb
* Content: [Get customer's direct signing status for Microsoft Customer Agreement. - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/get-direct-sign-status-of-customer-agreement#feedback)
* Content Source: [develop/get-direct-sign-status-of-customer-agreement.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/get-direct-sign-status-of-customer-agreement.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-sdk**
* GitHub Login: @JasonWHowell
* Microsoft Alias: **jasonh**

**Comment by JasonWHowell** [comment]
Sorry, we are slow to monitor and reply here. Consider asking the question in the Q&A forum. https://docs.microsoft.com/en-us/answers/topics/partner-center-api.html

**Comment by cf-jola** [comment]
Alright. I've made a post on there as well

**Comment by vijvala** [comment]
Please follow the direction on opening a CS support ticket to address your questions.


 https://docs.microsoft.com/en-us/partner-center/report-problems-with-partner-center
