### ISSUE TITLE
Billed Commercial Consumption Line Items (Back-Compat)

### ISSUE THREAD

**Issue by wudanbal** [MicrosoftDocs/partner-center-sdk#98]
When searching then billed API for **back-compatibility elements**, I'm not receiving a continuation token when there are more elements to be fetch/paged? Even though I clearly get the first 2000 elements (or whatever I set my fetchsize to), I don't get the continuation token when there are more items.

_https://docs.microsoft.com/en-us/partner-center/develop/get-invoice-billed-consumption-lineitems
This API also supports azure provider types for Microsoft Azure (MS-AZR-0145P) subscriptions. This means this API is a backward-compatible feature._

(using 1.15.3 Partner.Store.PartnerCenter)
partnerOperations.Invoices.ById(i.Id)
                            .By("azure", usagelineitems, "usd", period, fetchSize).Get()

Can anyone steer me in the right direction?

**Comment by JasonWHowell** [comment]
Sorry, we are slow to monitor and reply here. Consider asking the question in the Q&A forum. https://docs.microsoft.com/en-us/answers/topics/partner-center-api.html

**Comment by vijvala** [comment]
@wudanbal We don't monitory github queries, the best way to get your question answered is open a support ticket from partner center.
