### ISSUE TITLE
Does the Secure Application Model work with SDKs?

### ISSUE THREAD

**Issue by MSCRM-dev** [MicrosoftDocs/partner-center-sdk#99]
I have already done an integration using the SDKs (Microsoft.CrmSdk.CoreAssemblies 9.0) in C# but now for authentication purpose one of the customers is requesting the secure app model. As per this documentation, this model works with REST API. 
Shall I need to convert my C# integration code (that has used the SDK classes and methods) to the REST API? What is the solution to this so that I can only change in the way of authentication and the remaining things will work with SDKs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad81757a-da98-492e-aa46-cd920709432e
* Version Independent ID: fbf50fa1-8698-5e30-483b-2408426d349d
* Content: [Enable secure application model - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/enable-secure-app-model#feedback)
* Content Source: [develop/enable-secure-app-model.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/enable-secure-app-model.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-csp**
* GitHub Login: @JasonWHowell
* Microsoft Alias: **jasonh**

**Comment by JasonWHowell** [comment]
Sorry, we are slow to monitor and reply here. Consider asking the question in the Q&A forum. https://docs.microsoft.com/en-us/answers/topics/partner-center-api.html

**Comment by vijvala** [comment]
Please follow -https://github.com/microsoft/Partner-Center-DotNet-Samples/blob/master/secure-app-model/keyvault/CSPApplication/Program.cs
